version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - dem

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5000:80"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - dem

  app:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/apps_python
    depends_on:
      - postgres
    ports:
      - "9999:80"
    env_file:
      - ./backend/.env
    networks:
      - dem

networks:
  dem:

volumes:
  pgdata:
